### ISSUE TITLE
BrassAmber's BattleTowers Crash on launch

### ISSUE THREAD

**Issue by guivnf** [infernalstudios/JSON-Entity-Models#11]
### Describe the Bug

So every time i launch my game both with JEMs (geckolib) and BrassAmbers Battletowers my game crashes, it doesn't even get to the menu screen (where you have the singleplayer,multiplayer buttons), it just crashes before that. It seems as if its some issues with accesstransformers, well, i'd be glad if you guys could have a look at this.

### Reproduction Steps

1. download geckolib, Jems and bras amber's battle towers
2. launch game
3. crash

### Expected Result

The expected result was the game was supposed to launch

### Screenshots and Videos

There isn't any video, it just crashes thats it.

Mind that in the info below the Mod version is: 0.2.1 i think you guys forgot to add in new options there !

### Operating System

Windows 10

### Mod Version

0.1.0

### Minecraft Version

1.18.2

### Forge Version

40.2.0

### Other Mods

Brass amber's battletowers

### Additional Context

No additional context, here's the log: https://mclo.gs/TU55oMj

**Comment by Dariensg** [comment]
This crash has nothing to do with JEMs. It's caused by a bad resource path from Brass Ambers BattleTowers. Please report it to them. But, thank you for reminding me about adding new versions to the bug report! Totally forgot to!
